name:                ollama-haskell
version:             0.1.3.0
github:              "tusharad/ollama-haskell"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2024 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Haskell client for ollama.
category:            Web
description:         Ollama client for Haskell

dependencies:
- base >= 4.7 && < 5
- aeson 
- bytestring
- text 
- time
- http-client 
- http-client-tls
- http-types 
- base64-bytestring
- filepath
- directory
- containers
- stm
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - ImportQualifiedPost

tests:
  ollama-haskell-test:
    main:                Main.hs
    source-dirs:         test
    default-extensions:
      - ImportQualifiedPost
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ollama-haskell
    - tasty
    - tasty-hunit
    - text
    - silently
    - aeson
